In [13]:
import numpy as np
np.random.seed(0)
x1=np.random.randint(12,size=(4))
print(x1)
print(x1[1::2])
print(x1[::-1])
print(x1[1:4:2])
x1[2]=4
print(x1[:3:1])
print(x1[::2])
print(x1)

[ 5  0  3 11]
[ 0 11]
[11  3  0  5]
[ 0 11]
[5 0 4]
[5 4]
[ 5  0  4 11]


In [6]:
import numpy as np
np.random.seed(0)
x2=np.random.randint(6,size=(3,3))
print(x2)
print(x2[:,0])
print(x2[0,:])
print(x2[:,])

[[4 5 0]
 [3 3 3]
 [1 3 5]]
[4 3 1]
[4 5 0]
[[4 5 0]
 [3 3 3]
 [1 3 5]]


In [15]:
import numpy as np
np.random.seed(0)
x3=np.random.randint(9,size=(3,3))
print(x3)
print(x3[::3])
print(x3[0,:])

[[5 0 3]
 [3 7 3]
 [5 2 4]]
[[5 0 3]]
[5 0 3]


In [1]:
import numpy as np
np.random.seed(0)
x3=np.random.randint(9,size=(3,3))
print(x3)
print(x3[:,2])


[[5 0 3]
 [3 7 3]
 [5 2 4]]
[3 3 4]
