In [4]:
import numpy as np
np.random.seed(0)
x=np.array([1,2,4])
y=np.array([6,7,9])
np.concatenate([x,y])  #row wise or vertically

array([1, 2, 4, 6, 7, 9])

In [8]:
import numpy as np
np.random.seed(0)
x=np.array([1,2,4])
y=np.array([6,7,9])
np.concatenate([x,y],axis=0) #default value is 0

array([1, 2, 4, 6, 7, 9])

In [11]:
import numpy as np
np.random.seed(0)
x=np.random.randint(10,size=(3,4))
y=np.array([6,7,9])
np.concatenate([x,x],axis=1) # for column wise

array([[5, 0, 3, 3, 5, 0, 3, 3],
       [7, 9, 3, 5, 7, 9, 3, 5],
       [2, 4, 7, 6, 2, 4, 7, 6]])

In [14]:
import numpy as np
np.random.seed(0)
x=np.random.randint(10,size=(3,4))
y=np.array([6,7,9])
np.concatenate([x,x],axis=1) # for column wise
np.vstack([x,x])

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6],
       [5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [16]:
import numpy as np
np.random.seed(0)
x=np.random.randint(10,size=(3,4))
y=np.array([6,7,9,7])
np.concatenate([x,x],axis=1) # for column wise
np.vstack([y,x])

array([[6, 7, 9, 7],
       [5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [33]:
import numpy as np
np.random.seed(0)
x=np.random.randint(10,size=(3,4))
print(x)
y=np.array([6,7,9,7])

np.concatenate([x,x],axis=1) # for column wise


[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


array([[5, 0, 3, 3, 5, 0, 3, 3],
       [7, 9, 3, 5, 7, 9, 3, 5],
       [2, 4, 7, 6, 2, 4, 7, 6]])

In [28]:
x2=[1,2,3,4,5,6,7,8]
a,b,c=np.split(x2,[3,5])
print(a)
print(b)
print(c)

[1 2 3]
[4 5]
[6 7 8]


In [34]:
import numpy as np
np.random.seed(0)

x = np.random.randint(10, size=(3,4))
print("x:\n", x)

y = np.array([6,7,9])   # must have 3 elements (same as rows in x)

# Column-wise concatenate
result1 = np.concatenate([x, x], axis=1)
print("\nConcatenate column-wise:\n", result1)

# Add y as a new column
result2 = np.hstack([x, y.reshape(-1,1)])
print("\nAfter adding y as column:\n", result2)


x:
 [[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]

Concatenate column-wise:
 [[5 0 3 3 5 0 3 3]
 [7 9 3 5 7 9 3 5]
 [2 4 7 6 2 4 7 6]]

After adding y as column:
 [[5 0 3 3 6]
 [7 9 3 5 7]
 [2 4 7 6 9]]


In [40]:
import numpy as np
np.random.seed(0)
x=np.random.randint(10,size=(3,4))
y=np.array([6,7,9])
np.concatenate([x,x],axis=1) # for column wise
np.hstack([x,y.reshape([-1,1])])


array([[5, 0, 3, 3, 6],
       [7, 9, 3, 5, 7],
       [2, 4, 7, 6, 9]])