In [2]:
import numpy as np
np.random.seed(0)
x1=np.random.randint(9,size=(5))
print(x1)
x1_sub=x1[:4]
print(x1_sub)

[5 0 3 3 7]
[5 0 3 3]


In [4]:
import numpy as np
np.random.seed(0)
grid=np.arange(1,11)
print(grid)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
import numpy as np
np.random.seed(0)
grid=np.arange(1,11)
print(grid)
grid_1=np.array([1,2,4,5,3,6,7,9])
print(grid_1)

[ 1  2  3  4  5  6  7  8  9 10]
[1 2 4 5 3 6 7 9]


In [18]:
import numpy as np
np.random.seed(0)
grid=np.arange(1,10).reshape(3,3)
print(grid)
grid_1=np.array([1,2,4,5,3,6,7,9])
print(grid_1)
print(grid_1.reshape(1,8))  #it will give elements
grid[np.newaxis,:]


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 4 5 3 6 7 9]
[[1 2 4 5 3 6 7 9]]


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [19]:
import numpy as np
np.random.seed(0)
grid=np.arange(1,10).reshape(3,3)
print(grid)
grid_1=np.array([1,2,4,5,3,6,7,9])
print(grid_1)
print(grid_1.reshape(1,8))  #it will give elements
grid[:np.newaxis]


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 4 5 3 6 7 9]
[[1 2 4 5 3 6 7 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
import numpy as np
np.random.seed(0)
x1=np.random.randint(9,size=(5))
print(x1)
x1_sub=x1[:4]
print(x1_sub)

[5 0 3 3 7]
[5 0 3 3]
