In [9]:
import numpy as np
x=np.random.rand(10,2)
%matplotlib inline
#to render plot inline or else some sub window is opened
import matplotlib.pyplot as plt
import seaborn; 
#it is for styling the charts created that are created using matplotlib,it is a lib created using on top of matplotlib
seaborn.set() #plot styling
plt.scatter(x[:,0],x[:,1],s=100); #it will create a scatter plot for all the x and y coordinates for s
#s is the size of each point in the scatterplot
dist_sq=np.sum((x[:,np.newaxis,:]-x[np.newaxis,:,:])**2,axis=-1)
# it will create a new axis for the x coordinate and new axis for the y coordinate
#the size of x is 10*2
differences=x[:,np.newaxis,:]-x[np.newaxis,:,:]
differences.shape
sq_differences=differences**2
sq_differences.shape
dist_sq=sq_differences.sum(-1)
dist_sq.shape
print(dist_sq.shape)
dist_sq.diagonal()
nearest=np.argsort(dist_sq,axis=1)
print(nearest)
k=2
nearest_partition=np.argpartition(dist_sq,k+1,axis=1)
print(nearest_partition)
plt.scatter(x[:,0],x[:1],s=100)
for i in range(x.shape[0]):
    for j in nearest_partition[i,:k+1]:
        plt.plot(*zip(x[j],x[i]),color='black')
        
    
#no of points are 10 so the loop i will work from index position 0 to 9 for all the 10 points
#k is the hyper parameter the value 2 defines 2 nearset neighbours for each point 
#np.argpartition find the indexies of k+1 smallest distances of each row withou fully sorting it
#this will add a new axis in the middle x[:,np.newaxis,:]
#this will add a new axis in the start x[:,np.newaxis,:,:]
#:k+1 means the loop will execute for the first 3 enteries for each index i in the nearest partition array
#zip function will pair the coordinates of i and the coordinates odf itds neighbour that is j together and a black line will be created between i and j.

(10, 10)
[[0 1 9 2 5 3 7 8 6 4]
 [1 0 5 9 7 2 3 8 6 4]
 [2 9 3 5 8 6 0 7 4 1]
 [3 9 2 4 6 8 5 0 7 1]
 [4 6 3 8 2 9 5 7 0 1]
 [5 7 2 9 8 1 0 6 3 4]
 [6 8 4 2 9 3 5 7 0 1]
 [7 5 8 2 9 1 6 0 3 4]
 [8 6 2 5 4 7 9 3 0 1]
 [9 2 3 5 0 8 6 7 1 4]]
[[1 0 9 2 5 3 7 8 6 4]
 [1 0 5 9 3 2 6 7 8 4]
 [3 2 9 5 8 6 0 7 1 4]
 [3 9 2 4 1 5 6 7 8 0]
 [3 6 4 8 2 9 5 7 1 0]
 [5 7 2 9 1 8 0 6 3 4]
 [6 8 4 2 9 5 1 7 3 0]
 [5 7 8 2 9 1 6 0 3 4]
 [8 6 2 5 4 7 9 1 3 0]
 [2 9 3 5 0 1 6 7 8 4]]


ValueError: x and y must be the same size