In [11]:
import numpy as np
#sortingarray
x=np.array([2,1,4,3,5])
#simple selection sort
def selection_sort(x):
    for i in range(len(x)):
        swap=i+np.argmin(x[i:])
        (x[i],x[swap])=(x[swap],x[i])
        return x
print(selection_sort(x))

[1 2 4 3 5]


In [7]:

import numpy as np
#sortingarray
x=np.array([2,1,4,3,5])
def bogosort(x):
    while np.any(x[:-1]>x[1:]):
        np.random.shuffle(x)
        return x
bogosort(x)      
#complexity(n*n!)

array([2, 1, 3, 5, 4])

In [12]:
import numpy as np
#sortingarray
x=np.array([2,1,4,3,5])
np.sort(x)
x.sort()
print(x)
x=np.array([2,1,4,5,6])
i=np.argsort(x)
x[i]
#complexity(O(nlogn))
#it is based on quick sort
#inplace-like sort array(here index is not specified)


[1 2 3 4 5]


array([1, 2, 4, 5, 6])