In [3]:
import numpy as np
array1=np.arange(16).reshape((4,4))
a1,a2=np.vsplit(array1,[2])
b1,b2=np.hsplit(array1,[2])
print(a1,a2)
print(b1,b2)

[[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
