In [12]:
import numpy as np
name=['alice','Bob','cathy','doug']
#structured data provides efficient storage for compound heterogeneous data 
#when we have several categorical data we will be using structured data in which each element is record with multiple fields
age=[25,45,37,19]
weight=[55.0,85.5,68.0,61.5]
x=np.zeros(4,dtype=int)
print(x)
#use a compound data type or structured arrays
data=np.zeros(4,dtype={'names':('name','age','weight'),'formats':('U10','i4','f8')})
print(data.dtype)
print(data)
data['name']=name
data['age']=age
data['weight']=weight
#unicode string of length 10-U10
#I4-4byte integer
#f8-float
data[0]
data[-1]['name']
data[data['age'] < 30]['name']


[0 0 0 0]
[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]
[('', 0, 0.) ('', 0, 0.) ('', 0, 0.) ('', 0, 0.)]


array(['alice', 'doug'], dtype='<U10')

In [16]:
#Creating the Structured array
#strcuctured an be created using dic or set of tuples
np.dtype({'names':('name','age','weight'),'formats':('U10','i4','f8')})
np.dtype({'names':('name','age','weight'),'formats':((np.str_,10),int ,np.float32)})
np.dtype([('name','S10'),('age','i4'),('weight','f8')])
np.dtype('S10,i4,f8')
#it is for multi byte data like integer or float and it describes byte order
#<-little indian
#which will put the least significant bit first 
#>-bigindian
#which will put the most significant bit first 


dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

In [21]:
#more advanced compound types
import numpy as np
tp=np.dtype([('id','i8'),('mat','f8',(3,3))])
x=np.zeros(1,dtype=tp)
print(x[0])
print(x['mat'][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
